EXPERIMENT 10: Application of NLP

To perform sentiment classification using td-idf approach.

In [31]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [28]:
!unzip txt_sentoken.zip

Archive:  txt_sentoken.zip
replace txt_sentoken/neg/cv000_29416.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [29]:
movie_data = load_files("txt_sentoken")
X,y = movie_data.data, movie_data.target

Text Processing

In [30]:
documents = []
from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [32]:
for sen in range(0 , len(X)):
  document =  re.sub(r'\W',' ', str(X[sen]))
  document =  re.sub(r'\s+[a - zA - Z]\s+',' ', document)
  document =  re.sub(r'\^[a-zA-Z\s+]',' ', document)
  document =  re.sub(r'\s+',' ', document , flags = re.I)
  document =  re.sub(r'\^b\s+','', document)
  document = document.lower()
  document = document.split()
  document = [stemmer.lemmatize(word) for word in document]
  document = ' '.join(document)
  documents.append(document)


Converting Text to Numbers

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer  = CountVectorizer(max_features =  1500,  min_df = 5, max_df = 0.7, stop_words = stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [34]:
X[5]

array([0, 0, 0, ..., 0, 0, 1])

Tf-IDf

In [35]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [36]:
X[7]

array([0.        , 0.        , 0.        , ..., 0.        , 0.08164721,
       0.        ])

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(max_features = 1500, min_df =  5 ,max_df = 0.7 , stop_words = stopwords.words('english'))
X = tfidfconverter.fit_transform(documents).toarray()

In [38]:
X[5]

array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.04193868])

Training and Testing Sets

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state = 0)

In [42]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10000, random_state = 0)
classifier.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [43]:
y_pred = classifier.predict(X_test)

Evaluating the Model

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Confusion Matrix:" , confusion_matrix(y_test , y_pred))
print("Classification Report:" , classification_report(y_test , y_pred))
print("Accuracy:" , accuracy_score(y_test , y_pred))

Confusion Matrix: [[175  33]
 [ 32 160]]
Classification Report:               precision    recall  f1-score   support

           0       0.85      0.84      0.84       208
           1       0.83      0.83      0.83       192

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84      0.84       400

Accuracy: 0.8375


Saving and Loading the Model

In [46]:
with open('text_classifier' , 'wb') as picklefile:
  pickle.dump(classifier,picklefile)

In [47]:
with open('text_classifier' , 'rb') as training_model:
  model = pickle.load(training_model)

In [49]:
y_pred2 = model.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test , y_pred2))
print(accuracy_score(y_test , y_pred2))

[[175  33]
 [ 32 160]]
              precision    recall  f1-score   support

           0       0.85      0.84      0.84       208
           1       0.83      0.83      0.83       192

    accuracy                           0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84      0.84       400

0.8375
